### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by shoxie** [oceanroleplay/discord-music-bot#4] opened 2022-01-03 02:46 UTC
## Description
`/music play` return `TypeError: Cannot read properties of undefined (reading 'metadata')`. When i console the error on `YoutubePlayer/core/Queue.js:255` , i got 

`Error: Error: Cannot find module '@discordjs/opus'`
`Error: Cannot find module 'node-opus'`
`Error: Cannot find module 'opusscript'`

## Versions
- `discordjs` : `^13.5.0`
- `discordx` : `9.1.7`
- `Nodejs` :  `16.13.1`

## Steps to Reproduce the Problem

  1. Run `/music play`
  2. Console returns `TypeError: Cannot read properties of undefined (reading 'metadata')`

## Possible fix

Install `@discordjs/opus` `node-opus` `opusscript` with yarn/npm

**Comment by oceanroleplay** [comment] 2022-01-03 03:49
those are peer dependencies, you may receive console log warning when you do `npm install`, but it's my bad, I forget to mention this in installation guide

**Comment by oceanroleplay** [comment] 2022-01-03 04:33
@shoxie I have cloned and did `npm install` then `npm run dev`, I did not find any issue like described in your issue.

note: I have now updated dependencies to support latest version o deps.

**Comment by oceanroleplay** [comment] 2022-01-03 06:46
I am closing the issue for now, since it can not reproduced. Let me know if you have more informations.

**Closed by oceanroleplay** 2022-01-03 06:46 UTC

**Comment by oceanroleplay** [comment] 2022-01-04 20:26
the issue is appear to be having with `yarn`, I have now improved the core lib to do not catch these type of errors, so end user will now receive a clear view on what's wrong.
